"""Central constants for SecureVote PNG Phase 1."""

from __future__ import annotations

from datetime import timedelta

APP_NAME = "securevote_png"
API_V1_PREFIX = "/api/v1"
API_V2_PREFIX = "/api/v2"

DEFAULT_REQUEST_TIMEOUT_SECONDS = 10
DEFAULT_CONNECT_TIMEOUT_SECONDS = 3
DEFAULT_READ_TIMEOUT_SECONDS = 7
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_BACKOFF_SECONDS = 0.5
DEFAULT_CACHE_TTL_SECONDS = 300

TOKEN_TTL = timedelta(minutes=5)
TOKEN_CLOCK_SKEW = timedelta(seconds=30)
EMERGENCY_FREEZE_APPROVALS = 3
BREAK_GLASS_APPROVALS = 2
DEVICE_REATTESTATION_INTERVAL = timedelta(hours=24)
MAX_CLOCK_DRIFT_SECONDS = 120
MAX_VOTES_PER_TOKEN_PER_MINUTE = 1
MAX_VOTES_PER_DEVICE_PER_MINUTE = 10
AUDIT_HASH_ALGORITHM = "sha256"
PHASE1_ENCRYPTION_SCHEME = "AES-256-GCM"
PHASE1_SIGNATURE_SCHEME = "RSA-4096"
PHASE1_TOKEN_ALGORITHM = "RS256"