apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: securevote-ingress
spec:
  rules:
    - host: securevote.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
