"""Constants for the external NID client."""

VERIFY_ENDPOINT = "/api/v1/verify"
LOOKUP_ENDPOINT = "/api/v1/eligibility"
ENROLL_ENDPOINT = "/api/v1/enroll"
DEFAULT_TIMEOUT_SECONDS = 10
DEFAULT_CONNECT_TIMEOUT_SECONDS = 3
DEFAULT_CACHE_TTL_SECONDS = 300
DEFAULT_CIRCUIT_BREAKER_THRESHOLD = 5
DEFAULT_CIRCUIT_BREAKER_RESET_SECONDS = 60